#!/bin/bash
# .claude/hooks/save-java-docs.sh
# Java/Spring Boot関連の質問を自動的にdocs配下に保存するhook

INPUT=$(cat)
PROMPT=$(echo "$INPUT" | jq -r '.prompt // empty')

# Java/Spring Boot関連キーワードをチェック
if echo "$PROMPT" | grep -iE '(java|jvm|spring|springboot|spring boot|maven|gradle|jpa|hibernate|orm|bean|di|dependency|annotation|servlet|tomcat|gc|garbage collection|interface|class|method|package|junit|mockito|lambda|stream)' > /dev/null; then

  # ドキュメント保存ディレクトリを作成
  DOCS_DIR="$CLAUDE_PROJECT_DIR/docs"
  mkdir -p "$DOCS_DIR"

  # タイムスタンプとトピックに基づいたファイル名を生成
  TIMESTAMP=$(date +"%Y%m%d_%H%M%S")

  # トピックを抽出（最初の数単語を使用）
  TOPIC=$(echo "$PROMPT" | head -n 1 | sed 's/[^a-zA-Z0-9]/-/g' | tr '[:upper:]' '[:lower:]' | cut -c1-50 | sed 's/-*$//')

  FILENAME="$DOCS_DIR/java-${TOPIC}-${TIMESTAMP}.md"

  # プロンプトをマークダウンファイルに保存
  cat > "$FILENAME" << EOF
# Java/Spring Boot - $(date '+%Y-%m-%d %H:%M:%S')

## 質問

$PROMPT

## 回答

(Claudeによる回答がここに記録されます)

---
Generated by Claude Code Hook
EOF

  # 追加コンテキストをClaudeに返す
  echo "$INPUT" | jq --arg filename "$FILENAME" '{
    hookSpecificOutput: {
      hookEventName: "UserPromptSubmit",
      additionalContext: ("📝 Java/Spring Boot関連の質問を検知しました。ドキュメントを " + $filename + " に保存します。")
    }
  }'

  exit 0
fi

# Java関連でなければスルー
exit 0
